import type { LevelConfig, SectorConfig } from './types';

export const MENU_THEME_TRACK = 'theme_fractured_time.ogg';

export const SECTORS: SectorConfig[] = [
  {
    id: 1,
    name: 'Sektör 1: Asteroid Kuşağı',
    subtitle: 'İlk Savunma Hattı',
    description: 'Uzay istasyonunun sınır bölgesi. Mekanik ve siber düşman filolarının ilk taarruzu.',
    themeColor: '#00f3ff',
    gradient: ['#00f3ff', '#0072aa'],
    bgGlow: 'rgba(0, 243, 255, 0.25)',
    requiredLevel: 1,
    levelStart: 1,
    levelEnd: 8,
    iconName: 'Shield',
    ambientType: 'asteroids'
  },
  {
    id: 2,
    name: 'Sektör 2: Biyomekanik Kovan',
    subtitle: 'Biyo-Parazit İstilası & Asit Sisi',
    description: 'Canlı organik uzay gemileri, asit sporları ve biyolüminesans kovan tehdidi.',
    themeColor: '#10b981',
    gradient: ['#10b981', '#047857'],
    bgGlow: 'rgba(16, 185, 129, 0.25)',
    requiredLevel: 8,
    levelStart: 9,
    levelEnd: 16,
    iconName: 'Biohazard',
    ambientType: 'bio_spores'
  },
  {
    id: 3,
    name: 'Sektör 3: Takyon Tekilliği',
    subtitle: 'Boyutlararası Zaman Yırtığı',
    description: 'Zaman akışının büküldüğü, şeritler arası ışınlanan elit gemiler ve sonsuzluk patronu.',
    themeColor: '#a855f7',
    gradient: ['#c084fc', '#6b21a8'],
    bgGlow: 'rgba(168, 85, 247, 0.25)',
    requiredLevel: 16,
    levelStart: 17,
    levelEnd: 24,
    iconName: 'Clock',
    ambientType: 'tachyon_rift'
  }
];

export const LEVELS: LevelConfig[] = [
  // ═══════════════════════════════════════════════════════════════
  // SEKTÖR 1: ASTEROİD KUŞAĞI & İLK SAVUNMA HATTI (Bölüm 1 - 8)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 1,
    sectorId: 1,
    sectorName: 'Sektör 1: Asteroid Kuşağı',
    name: 'Bölüm 1: Keşif Devriyesi',
    subtitle: 'Uzay Sınırı Savunması',
    description: 'Uzay istasyonunun sınır bölgesi. Düşman keşif dronları ve hafif avcılar ilk dalgaları oluşturuyor.',
    themeColor: '#00f3ff',
    gradient: ['#00f3ff', '#0072aa'],
    difficultyMult: 1.0,
    miniBossName: 'GÖLGE AVCISI (Ağır Dron)',
    miniBossTitle: 'MİNİ BOSS • 4. DALGA',
    mainBossName: 'ASTEROİD PARÇALAYICI TİTAN',
    mainBossTitle: 'SEKTÖR PATRONU • 8. DALGA',
    ambientType: 'asteroids',
    enemyWeights: { drone: 55, scout: 35, speeder: 10 },
    spawnIntervalBase: 1.40,
    spawnCountBase: 7,
    musicTrack: 'theme_sector1_mining.ogg'
  },
  {
    id: 2,
    sectorId: 1,
    sectorName: 'Sektör 1: Asteroid Kuşağı',
    name: 'Bölüm 2: Plazma Fırtınası',
    subtitle: 'Yüksek Enerjili Radyasyon Bölgesi',
    description: 'Yoğun plazma bulutları arasında hızlı hız avcıları ve kalkanlı muhafızlar saldırıyor.',
    themeColor: '#ff2a5f',
    gradient: ['#ff2a5f', '#b30030'],
    difficultyMult: 1.15,
    miniBossName: 'KIZIL TAARRUZ ZIRHLISI',
    miniBossTitle: 'MİNİ BOSS • 4. DALGA',
    mainBossName: 'PLAZMA CEHENNEMİ KRUVAZÖRÜ',
    mainBossTitle: 'SEKTÖR PATRONU • 8. DALGA',
    ambientType: 'plasma',
    enemyWeights: { speeder: 35, drone: 30, scout: 25, siege: 10 },
    spawnIntervalBase: 1.30,
    spawnCountBase: 8,
    musicTrack: 'theme_sector2_alien_skies.ogg'
  },
  {
    id: 3,
    sectorId: 1,
    sectorName: 'Sektör 1: Asteroid Kuşağı',
    name: 'Bölüm 3: Siber Tersane',
    subtitle: 'Otomatik Üretim Fabrikaları',
    description: 'Düşman filolarının üretildiği devasa uzay tersanesi. Ağır bombardıman gemileri devriyede.',
    themeColor: '#ffd000',
    gradient: ['#ffd000', '#b38f00'],
    difficultyMult: 1.30,
    miniBossName: 'SİBER MUHAFIZ KULESİ',
    miniBossTitle: 'MİNİ BOSS • 4. DALGA',
    mainBossName: 'FABRİKA AMİRALİ PROMETHEUS',
    mainBossTitle: 'SEKTÖR PATRONU • 8. DALGA',
    ambientType: 'cyber_grid',
    enemyWeights: { siege: 40, shielded: 30, drone: 20, speeder: 10 },
    spawnIntervalBase: 1.25,
    spawnCountBase: 9,
    musicTrack: 'theme_sector3_station.ogg'
  },
  {
    id: 4,
    sectorId: 1,
    sectorName: 'Sektör 1: Asteroid Kuşağı',
    name: 'Bölüm 4: Kriyojenik İstasyon',
    subtitle: 'Mutlak Sıfır Karayolu',
    description: 'Dondurucu buz kristalleriyle kaplı terk edilmiş araştırma üssü. Zırhlı kalkanlı elitler yaklaşıyor.',
    themeColor: '#00d2ff',
    gradient: ['#6be5ff', '#005588'],
    difficultyMult: 1.45,
    miniBossName: 'BUZUL TAŞIYICI KRUVAZÖR',
    miniBossTitle: 'MİNİ BOSS • 4. DALGA',
    mainBossName: 'MUTLAK SIFIR GOLİATH',
    mainBossTitle: 'SEKTÖR PATRONU • 8. DALGA',
    ambientType: 'cryo_snow',
    enemyWeights: { shielded: 45, siege: 25, drone: 20, bomber: 10 },
    spawnIntervalBase: 1.20,
    spawnCountBase: 10,
    musicTrack: 'theme_sector4_lost_signal.ogg'
  },
  {
    id: 5,
    sectorId: 1,
    sectorName: 'Sektör 1: Asteroid Kuşağı',
    name: 'Bölüm 5: İyon Fırtınası',
    subtitle: 'Elektromanyetik Çöküş',
    description: 'Yüksek voltajlı iyon yıldırımları uzay boşluğuna yayılıyor. Hızlı ve çevik avcı birlikleri.',
    themeColor: '#a855f7',
    gradient: ['#c084fc', '#6b21a8'],
    difficultyMult: 1.60,
    miniBossName: 'ELEKTRO-ŞOK FIRTINASI',
    miniBossTitle: 'MİNİ BOSS • 4. DALGA',
    mainBossName: 'TESLA DREADNOUGHT TİTAN',
    mainBossTitle: 'SEKTÖR PATRONU • 8. DALGA',
    ambientType: 'ion_lightning',
    enemyWeights: { speeder: 45, scout: 35, shielded: 15, bomber: 5 },
    spawnIntervalBase: 1.15,
    spawnCountBase: 11,
    musicTrack: 'theme_sector5_beyond_stargate.ogg'
  },
  {
    id: 6,
    sectorId: 1,
    sectorName: 'Sektör 1: Asteroid Kuşağı',
    name: 'Bölüm 6: Hiçlik Yarığı',
    subtitle: 'Karanlık Madde Çekimi',
    description: 'Uzay-zaman dokusunun büküldüğü kara delik kenarı. Düşmanlar hiçlik kalkanlarıyla donatılmış.',
    themeColor: '#f59e0b',
    gradient: ['#f59e0b', '#7c2d12'],
    difficultyMult: 1.75,
    miniBossName: 'HİÇLİK GÖZETLEYİCİSİ',
    miniBossTitle: 'MİNİ BOSS • 4. DALGA',
    mainBossName: 'KARA DELİK HÜKÜMDARI',
    mainBossTitle: 'SEKTÖR PATRONU • 8. DALGA',
    ambientType: 'void_vortex',
    enemyWeights: { shielded: 35, bomber: 30, speeder: 20, siege: 15 },
    spawnIntervalBase: 1.10,
    spawnCountBase: 12,
    musicTrack: 'theme_sector6_singularity.ogg'
  },
  {
    id: 7,
    sectorId: 1,
    sectorName: 'Sektör 1: Asteroid Kuşağı',
    name: 'Bölüm 7: Kuantum Çekirdeği',
    subtitle: 'Enerji Reaktörü Savunması',
    description: 'Galaktik enerji santralini savunun. Ağır zırhlı bombardıman filoları reaktöre hücum ediyor.',
    themeColor: '#ff8800',
    gradient: ['#ffaa44', '#b35500'],
    difficultyMult: 1.90,
    miniBossName: 'KUANTUM DARBE KRUVAZÖRÜ',
    miniBossTitle: 'MİNİ BOSS • 4. DALGA',
    mainBossName: 'AŞIRI YÜKLÜ REAKTÖR TİTANI',
    mainBossTitle: 'SEKTÖR PATRONU • 8. DALGA',
    ambientType: 'quantum_pulse',
    enemyWeights: { bomber: 40, siege: 30, shielded: 20, speeder: 10 },
    spawnIntervalBase: 1.05,
    spawnCountBase: 13,
    musicTrack: 'theme_sector7_core_collapse.ogg'
  },
  {
    id: 8,
    sectorId: 1,
    sectorName: 'Sektör 1: Asteroid Kuşağı',
    name: 'Bölüm 8: Titan Çarpışması',
    subtitle: 'Sektör 1 Nihai Patronu',
    description: 'Sektör 1 komuta üssü. İlk galaktik titan boss ve ölümcül savaş kruvazörleri seni bekliyor!',
    themeColor: '#00ff88',
    gradient: ['#55ffaa', '#008844'],
    difficultyMult: 2.10,
    miniBossName: 'OMEGA MUHAFIZ KRUVAZÖRÜ',
    miniBossTitle: 'MİNİ BOSS • 4. DALGA',
    mainBossName: 'ASTEROİD PARÇALAYICI TİTAN',
    mainBossTitle: 'SEKTÖR PATRONU • 8. DALGA',
    ambientType: 'warp_tunnel',
    enemyWeights: { bomber: 25, speeder: 25, shielded: 25, siege: 25 },
    spawnIntervalBase: 1.00,
    spawnCountBase: 14,
    musicTrack: 'theme_sector8_edge_galaxy.ogg'
  },

  // ═══════════════════════════════════════════════════════════════
  // SEKTÖR 2: BİYOMEKANİK KOVAN & ASİT SİSİ (Bölüm 9 - 16)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 9,
    sectorId: 2,
    sectorName: 'Sektör 2: Biyomekanik Kovan',
    name: 'Bölüm 9: Biyo-Sinyal Sınırı',
    subtitle: 'Kovanın Dış Kabuğu',
    description: 'Organik parazit sinyallerinin başladığı bölge. Hızlı asit larva dronları sürü halinde saldırıyor.',
    themeColor: '#10b981',
    gradient: ['#10b981', '#047857'],
    difficultyMult: 2.25,
    miniBossName: 'ASİT TÜKÜREN KRALİÇE DRONU',
    miniBossTitle: 'MİNİ BOSS • 4. DALGA',
    mainBossName: 'ORGANİK KOVAN ÖNCÜSÜ',
    mainBossTitle: 'SEKTÖR PATRONU • 8. DALGA',
    ambientType: 'bio_spores',
    enemyWeights: { drone: 50, speeder: 30, scout: 20 },
    spawnIntervalBase: 1.05,
    spawnCountBase: 13,
    musicTrack: 'theme_scifi_2.ogg'
  },
  {
    id: 10,
    sectorId: 2,
    sectorName: 'Sektör 2: Biyomekanik Kovan',
    name: 'Bölüm 10: Kuluçka Koridoru',
    subtitle: 'Büyüme Odaları Savunması',
    description: 'Kuluçka keseleriyle çevrili dar koridor. Kalkanlı kuluçka muhafızları savunma hattını zorluyor.',
    themeColor: '#10b981',
    gradient: ['#34d399', '#065f46'],
    difficultyMult: 2.40,
    miniBossName: 'KULUÇKA MUHAFIZ KRUVAZÖRÜ',
    miniBossTitle: 'MİNİ BOSS • 4. DALGA',
    mainBossName: 'ASİT KOVAN FABRİKASI',
    mainBossTitle: 'SEKTÖR PATRONU • 8. DALGA',
    ambientType: 'bio_spores',
    enemyWeights: { shielded: 35, drone: 35, speeder: 20, siege: 10 },
    spawnIntervalBase: 1.00,
    spawnCountBase: 14,
    musicTrack: 'theme_scifi_3.ogg'
  },
  {
    id: 11,
    sectorId: 2,
    sectorName: 'Sektör 2: Biyomekanik Kovan',
    name: 'Bölüm 11: Kitin Zırhlı İstilacılar',
    subtitle: 'Rejenerasyon Tehdidi',
    description: 'Sert kitin kabuklu mutant avcılar. Hasar aldıkça zırhlarını sertleştiren canlı biyo-gemiler.',
    themeColor: '#84cc16',
    gradient: ['#a3e635', '#3f6212'],
    difficultyMult: 2.55,
    miniBossName: 'KİTİN MUHAFIZ DREADNOUGHT',
    miniBossTitle: 'MİNİ BOSS • 4. DALGA',
    mainBossName: 'MUTANT BİYOMEKANİK HİBRİT',
    mainBossTitle: 'SEKTÖR PATRONU • 8. DALGA',
    ambientType: 'bio_spores',
    enemyWeights: { scout: 40, shielded: 30, speeder: 20, bomber: 10 },
    spawnIntervalBase: 0.95,
    spawnCountBase: 14,
    musicTrack: 'theme_voidline.ogg'
  },
  {
    id: 12,
    sectorId: 2,
    sectorName: 'Sektör 2: Biyomekanik Kovan',
    name: 'Bölüm 12: Kraliçe Odası',
    subtitle: 'Kovan Kalbine Doğru • Mini Boss',
    description: 'Canlı organik kovanın kuluçka merkezi. Küçük parazitler fırlatan Kitin Kraliçesi seni bekliyor!',
    themeColor: '#a855f7',
    gradient: ['#c084fc', '#581c87'],
    difficultyMult: 2.70,
    miniBossName: 'KİTİN LEJYONER KRALİÇESİ',
    miniBossTitle: 'MİNİ BOSS • 4. DALGA',
    mainBossName: 'BİYO-KİTİN DREADNOUGHT TİTANI',
    mainBossTitle: 'SEKTÖR PATRONU • 8. DALGA',
    ambientType: 'bio_spores',
    enemyWeights: { shielded: 40, speeder: 30, bomber: 20, siege: 10 },
    spawnIntervalBase: 0.92,
    spawnCountBase: 15,
    musicTrack: 'theme_scifi_4.ogg'
  },
  {
    id: 13,
    sectorId: 2,
    sectorName: 'Sektör 2: Biyomekanik Kovan',
    name: 'Bölüm 13: Nöral Ağ Bağlantısı',
    subtitle: 'Biyo-Beyin Hatları',
    description: 'Tüm kovanı kontrol eden biyolojik sinir ağı. Kamikaze patlayıcı spor gemileri hızla hücum ediyor.',
    themeColor: '#10b981',
    gradient: ['#2dd4bf', '#134e4a'],
    difficultyMult: 2.85,
    miniBossName: 'SİNİR AĞI PARÇALAYICISI',
    miniBossTitle: 'MİNİ BOSS • 4. DALGA',
    mainBossName: 'NÖRAL BEYİN LEVİATHANI',
    mainBossTitle: 'SEKTÖR PATRONU • 8. DALGA',
    ambientType: 'bio_spores',
    enemyWeights: { speeder: 40, bomber: 30, drone: 20, shielded: 10 },
    spawnIntervalBase: 0.90,
    spawnCountBase: 15,
    musicTrack: 'theme_wormhole.ogg'
  },
  {
    id: 14,
    sectorId: 2,
    sectorName: 'Sektör 2: Biyomekanik Kovan',
    name: 'Bölüm 14: Asit Gölleri Geçidi',
    subtitle: 'Korozif Çukur Savunması',
    description: 'Derin korozif asit çukurları üzerinden ilerleyin. Ağır asit fırlatan biyo-kuşatma gemileri sahnede.',
    themeColor: '#84cc16',
    gradient: ['#bef264', '#4d7c0f'],
    difficultyMult: 3.00,
    miniBossName: 'KOROZİF KUŞATMA LEVİATHANI',
    miniBossTitle: 'MİNİ BOSS • 4. DALGA',
    mainBossName: 'ASİT CEHENNEMİ GOLİATH',
    mainBossTitle: 'SEKTÖR PATRONU • 8. DALGA',
    ambientType: 'bio_spores',
    enemyWeights: { siege: 40, bomber: 30, shielded: 20, speeder: 10 },
    spawnIntervalBase: 0.88,
    spawnCountBase: 16,
    musicTrack: 'theme_signals_across.ogg'
  },
  {
    id: 15,
    sectorId: 2,
    sectorName: 'Sektör 2: Biyomekanik Kovan',
    name: 'Bölüm 15: Kovanın Kalbi',
    subtitle: 'Organik Rezonans',
    description: 'Ana kovanın en korunaklı derinlikleri. Elit biyomekanik muhafız filosu son direnç hattını kuruyor.',
    themeColor: '#10b981',
    gradient: ['#6ee7b7', '#047857'],
    difficultyMult: 3.15,
    miniBossName: 'ELİT KOVAN SAVUNUCUSU',
    miniBossTitle: 'MİNİ BOSS • 4. DALGA',
    mainBossName: 'PROTO-HIVE PRECURSOR',
    mainBossTitle: 'SEKTÖR PATRONU • 8. DALGA',
    ambientType: 'bio_spores',
    enemyWeights: { shielded: 35, siege: 25, bomber: 25, speeder: 15 },
    spawnIntervalBase: 0.85,
    spawnCountBase: 16,
    musicTrack: 'theme_scifi_5.ogg'
  },
  {
    id: 16,
    sectorId: 2,
    sectorName: 'Sektör 2: Biyomekanik Kovan',
    name: 'Bölüm 16: Kovan Leviathanı',
    subtitle: 'Sektör 2 Nihai Patronu',
    description: 'Kovanın canlı tanrısı. Canlı çok uzantılı gövdesiyle asit dalgaları ve parazit fırtınası saçan dev titan!',
    themeColor: '#059669',
    gradient: ['#34d399', '#064e3b'],
    difficultyMult: 3.35,
    miniBossName: 'KOVAN MUHAFIZ BAŞBUĞU',
    miniBossTitle: 'MİNİ BOSS • 4. DALGA',
    mainBossName: 'PROTO-HIVE LEVIATHAN (ANA KOVAN TİTANI)',
    mainBossTitle: 'SEKTÖR PATRONU • 8. DALGA',
    ambientType: 'bio_spores',
    enemyWeights: { bomber: 30, siege: 30, shielded: 25, speeder: 15 },
    spawnIntervalBase: 0.82,
    spawnCountBase: 17,
    musicTrack: 'theme_starfall.ogg'
  },

  // ═══════════════════════════════════════════════════════════════
  // SEKTÖR 3: TAKYON TEKİLLİĞİ & ZAMAN BÜKÜLMESİ (Bölüm 17 - 24)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 17,
    sectorId: 3,
    sectorName: 'Sektör 3: Takyon Tekilliği',
    name: 'Bölüm 17: Boyut Yırtığı Kapısı',
    subtitle: 'Kırılan Gerçeklik',
    description: 'Uzay-zaman sürekliliğinin parçalandığı boyut kapısı. Klonlanan zamansal illüzyon gemileri ilk dalgada.',
    themeColor: '#38bdf8',
    gradient: ['#38bdf8', '#0284c7'],
    difficultyMult: 3.50,
    miniBossName: 'FAZ İLLÜZYONİST KRUVAZÖRÜ',
    miniBossTitle: 'MİNİ BOSS • 4. DALGA',
    mainBossName: 'BOYUT YIRTICISI TİTAN',
    mainBossTitle: 'SEKTÖR PATRONU • 8. DALGA',
    ambientType: 'tachyon_rift',
    enemyWeights: { speeder: 45, scout: 35, drone: 20 },
    spawnIntervalBase: 0.85,
    spawnCountBase: 16,
    musicTrack: 'theme_warp.ogg'
  },
  {
    id: 18,
    sectorId: 3,
    sectorName: 'Sektör 3: Takyon Tekilliği',
    name: 'Bölüm 18: Takyon Akıntısı',
    subtitle: 'Dengesiz Zaman Akışı',
    description: 'Takyon parçacıkları savaş alanındaki zamanı hızlandırıyor. Hızı anlık değişen dengesiz hız avcıları.',
    themeColor: '#6366f1',
    gradient: ['#818cf8', '#4338ca'],
    difficultyMult: 3.65,
    miniBossName: 'TAKYON HIZ DREADNOUGHT',
    miniBossTitle: 'MİNİ BOSS • 4. DALGA',
    mainBossName: 'AKINTI SÜVARİSİ AEON',
    mainBossTitle: 'SEKTÖR PATRONU • 8. DALGA',
    ambientType: 'tachyon_rift',
    enemyWeights: { speeder: 50, shielded: 25, scout: 25 },
    spawnIntervalBase: 0.82,
    spawnCountBase: 16,
    musicTrack: 'theme_long_jump.ogg'
  },
  {
    id: 19,
    sectorId: 3,
    sectorName: 'Sektör 3: Takyon Tekilliği',
    name: 'Bölüm 19: Paralel Evren Filosu',
    subtitle: 'Zaman Aynası Direnişi',
    description: 'Paralel gerçekliklerden gelen savaş gemileri. Geri sarma kalkanlarıyla öldükten sonra dirilen elitler.',
    themeColor: '#a855f7',
    gradient: ['#c084fc', '#7e22ce'],
    difficultyMult: 3.80,
    miniBossName: 'PARALEL YANSIMA AMİRALİ',
    miniBossTitle: 'MİNİ BOSS • 4. DALGA',
    mainBossName: 'ZAMAN AYNASI SAVAŞ GEMİSİ',
    mainBossTitle: 'SEKTÖR PATRONU • 8. DALGA',
    ambientType: 'tachyon_rift',
    enemyWeights: { shielded: 40, bomber: 30, speeder: 20, siege: 10 },
    spawnIntervalBase: 0.80,
    spawnCountBase: 17,
    musicTrack: 'theme_signal_beyond.ogg'
  },
  {
    id: 20,
    sectorId: 3,
    sectorName: 'Sektör 3: Takyon Tekilliği',
    name: 'Bölüm 20: Zaman Kulesi',
    subtitle: 'Zaman Muhafızı • Mini Boss',
    description: 'Boyutlararası zaman kulesi. Zamanı durduran ve oyuncunun taş kaydırmasını donduran Krono Muhafızı!',
    themeColor: '#f59e0b',
    gradient: ['#fbbf24', '#b45309'],
    difficultyMult: 4.00,
    miniBossName: 'KRONO MUHAFIZ AEON',
    miniBossTitle: 'MİNİ BOSS • 4. DALGA',
    mainBossName: 'ZAMAN BEKÇİSİ CHRONOS',
    mainBossTitle: 'SEKTÖR PATRONU • 8. DALGA',
    ambientType: 'tachyon_rift',
    enemyWeights: { shielded: 35, siege: 30, speeder: 20, bomber: 15 },
    spawnIntervalBase: 0.78,
    spawnCountBase: 17,
    musicTrack: 'theme_sector5_beyond_stargate.ogg'
  },
  {
    id: 21,
    sectorId: 3,
    sectorName: 'Sektör 3: Takyon Tekilliği',
    name: 'Bölüm 21: Entropi Çöküşü',
    subtitle: 'Kozmik Madde Çöküşü',
    description: 'Yerçekimi ve zaman dengesinin bozulduğu yıkım alanı. Kozmik yerçekimi bombardıman kruvazörleri.',
    themeColor: '#ef4444',
    gradient: ['#f87171', '#991b1b'],
    difficultyMult: 4.20,
    miniBossName: 'ENTROPİ YIKIM TİTANI',
    miniBossTitle: 'MİNİ BOSS • 4. DALGA',
    mainBossName: 'SİNGULARİTY KRALİÇESİ',
    mainBossTitle: 'SEKTÖR PATRONU • 8. DALGA',
    ambientType: 'tachyon_rift',
    enemyWeights: { bomber: 40, siege: 30, shielded: 20, speeder: 10 },
    spawnIntervalBase: 0.75,
    spawnCountBase: 18,
    musicTrack: 'theme_sector6_singularity.ogg'
  },
  {
    id: 22,
    sectorId: 3,
    sectorName: 'Sektör 3: Takyon Tekilliği',
    name: 'Bölüm 22: Boyutlararası Araf',
    subtitle: 'Faz Değiştirenler',
    description: 'Şeritler arasında ışınlanarak saldıran elit faz kruvazörleri. Savunma kalkanını dört bir yandan zorluyorlar.',
    themeColor: '#8b5cf6',
    gradient: ['#a78bfa', '#5b21b6'],
    difficultyMult: 4.40,
    miniBossName: 'FAZ SAVAŞÇISI BAŞKOMUTAN',
    miniBossTitle: 'MİNİ BOSS • 4. DALGA',
    mainBossName: 'ARAF CELLADI TİTAN',
    mainBossTitle: 'SEKTÖR PATRONU • 8. DALGA',
    ambientType: 'tachyon_rift',
    enemyWeights: { speeder: 35, shielded: 30, siege: 20, bomber: 15 },
    spawnIntervalBase: 0.72,
    spawnCountBase: 18,
    musicTrack: 'theme_scifi_3.ogg'
  },
  {
    id: 23,
    sectorId: 3,
    sectorName: 'Sektör 3: Takyon Tekilliği',
    name: 'Bölüm 23: Gerçekliğin Kenarı',
    subtitle: 'Nihai Kapı Öncesi Son Direnç',
    description: 'Tüm elementlere karşı dayanıklı son muhafız filosu. Nihai patronun kapısındaki son büyük engel!',
    themeColor: '#ec4899',
    gradient: ['#f472b6', '#9d174d'],
    difficultyMult: 4.60,
    miniBossName: 'SONSUZLUK ÖNCÜ KRUVAZÖRÜ',
    miniBossTitle: 'MİNİ BOSS • 4. DALGA',
    mainBossName: 'GERÇEKLİK KORUYUCUSU TİTAN',
    mainBossTitle: 'SEKTÖR PATRONU • 8. DALGA',
    ambientType: 'tachyon_rift',
    enemyWeights: { bomber: 30, siege: 30, shielded: 25, speeder: 15 },
    spawnIntervalBase: 0.70,
    spawnCountBase: 19,
    musicTrack: 'theme_scifi_4.ogg'
  },
  {
    id: 24,
    sectorId: 3,
    sectorName: 'Sektör 3: Takyon Tekilliği',
    name: 'Bölüm 24: Sonsuzluk Titani',
    subtitle: 'Galaktik Nihai Patron • Son Savaş',
    description: 'Tüm evrenin kaderini belirleyecek nihai savaş! Geçmiş ve Gelecek fazlarında saldıran CHRONOS OVERLORD!',
    themeColor: '#ffd000',
    gradient: ['#fde047', '#b45309'],
    difficultyMult: 5.00,
    miniBossName: 'CHRONOS BAŞ MUHAFIZI',
    miniBossTitle: 'MİNİ BOSS • 4. DALGA',
    mainBossName: 'CHRONOS OVERLORD - ETERNITY PRIME (NİHAİ TİTAN)',
    mainBossTitle: 'GALAKTİK NİHAİ PATRON • 8. DALGA',
    ambientType: 'tachyon_rift',
    enemyWeights: { bomber: 25, siege: 25, shielded: 25, speeder: 25 },
    spawnIntervalBase: 0.65,
    spawnCountBase: 20,
    musicTrack: 'theme_sector8_edge_galaxy.ogg'
  }
];

export const TOTAL_LEVELS = LEVELS.length;

export function getLevelConfig(levelId: number): LevelConfig {
  return LEVELS.find(l => l.id === levelId) || LEVELS[0];
}

export function getSectorConfig(sectorId: number): SectorConfig {
  return SECTORS.find(s => s.id === sectorId) || SECTORS[0];
}

export function getSectorForLevel(levelId: number): SectorConfig {
  const level = getLevelConfig(levelId);
  return getSectorConfig(level.sectorId);
}

export function getSectorLevels(sectorId: number): LevelConfig[] {
  return LEVELS.filter(l => l.sectorId === sectorId);
}
